045 - Add login & register layouts
IhorMruchko/ScheduleLNU pull request #49
Opened 2022-05-01 18:56 UTC by TitanMaiden

2022-05-01 19:07 UTC, IhorMruchko requested changes

2022-05-01 19:07 UTC, IhorMruchko commented on ScheduleLNU.Presentation/Areas/Authentication/Views/Register/Register.cshtml
> +                                    <a href="reset.html" class="forget-link">Forgot password?</a>
Change "forgot password" to "already have an account"

2022-05-02 02:13 UTC, qwerhnatkiv commented on ScheduleLNU.Presentation/Areas/Authentication/Controllers/LoginController.cs
> +    [Route("[area]/login")]
do we realy need use "authentication" as part of the our url?

2022-05-02 02:15 UTC, qwerhnatkiv approved these changes

2022-05-02 05:45 UTC, TitanMaiden commented on ScheduleLNU.Presentation/Areas/Authentication/Controllers/LoginController.cs
> +    [Route("[area]/login")]
Yes, for consistency

2022-05-02 07:01 UTC, IhorMruchko approved these changes

2022-05-02 08:13 UTC, merged